### ISSUE TITLE
FFMPEG files missing after starting container

### ISSUE THREAD

**Issue by henryjb99** [mdhiggins/radarr-sma#21]
When I start the container, my /usr/local/bin directory is empty. When I pull the logs, I get the following info:
 [cont-init.d] 90-sma-config: executing...
 xz: (stdin): File format not recognized
 tar: Child returned status 1
 tar: Error is not recoverable: exiting now
 chown: cannot access '/usr/local/bin/ffmpeg': No such file or directory
 chown: cannot access '/usr/local/bin/ffprobe': No such file or directory
 chmod: cannot access '/usr/local/bin/ffmpeg': No such file or directory
 chmod: cannot access '/usr/local/bin/ffprobe': No such file or directory
 [cont-init.d] 90-sma-config: exited 0.

Reruns will sometimes fix the issue.

**Comment by mdhiggins** [comment]
When I switched over building from Dockerhub to Github actions I kept running into issues where the FFMPEG binary download would time out. It would seem https://www.johnvansickle.com/ffmpeg/ which is where the binaries are from has some sort of request limit and it was getting blocked. As a result I moved the ffmpeg download from the build side of the container to startup. Its certainly possible that you may also be having your request blocked intermittently seeing the same issue.

I did contact the developer and provided him the list of IP addresses that makeup github actions since docker hub was apparently given special privileges but I haven't heard back. Fortunately however by timing the build during off-peak hours I am able to get it to work most of the time so I've been able to restore the ffmpeg binaries during the build phase and thus included in the image
