### ISSUE TITLE
Last nightly build?

### ISSUE THREAD

**Issue by preacher65** [mdhiggins/radarr-sma#25]
Hi, apologies if I've misunderstood something, but just wanted to understand the cadence of the nightly builds, and to know what to expect.

I'm using the nightly tag, but currently on 3.1.0.4700, which is about a month old. Are the nightly builds automated or do they have to done manually? From checking here and on hub, it looks like they are possibly manual, which is of course fine and I'm not chasing for an update, just wanted to check my assumptions are correct.

Thanks.

**Comment by mdhiggins** [comment]
Its updated weekly and I've been having issues with automated builds failing because the ffmpeg binary server is blocking requests from github actions and timing out. For now if you want true nightly builds its better to build yourself from your own IP address until I have a solution. I've reached out to the host of the ffmpeg binaries but still waiting on a reply

**Comment by preacher65** [comment]
Understood - thanks for the quick reply.

**Comment by mdhiggins** [comment]
I've updated all the sma containers to not pull ffmpeg during build time but instead during first launch which dodges the IP issue and have now scheduled the nightly build to rebuild each night instead of weekly

**Comment by preacher65** [comment]
Just saw that it had updated, but hadn't realised it was because you'd made a change. That's fantastic, thanks!

I was struggling getting it to build locally, due to issues with the container connecting to the internet during the apt-get phase, and I'm still on a learning journey with docker.

Really appreciate you taking the time and effort to change it.
