### ISSUE TITLE
Need to install Intel Non-Free driver?

### ISSUE THREAD

**Issue by tjfriese** [mdhiggins/radarr-sma#42]
I had to install the Intel non free driver (sudo docker exec -it Sonarr apt install intel-media-va-driver-non-free -y) to get vaapi hardware acceleration to work in Sonarr.

I have tried the same command in my Radarr docker, but receive the following error: 

OCI runtime exec failed: exec failed: container_linux.go:367: starting container process caused: exec: "apt": executable file not found in $PATH: unknown

Do I need to install the non-free driver and if so how can I do that without apt?

**Comment by mdhiggins** [comment]
The Radarr container is based on alpine linux and uses apk not apt, and uses an entirely different set of packages

You can see

https://github.com/mdhiggins/radarr-sma/blob/build/root/etc/cont-init.d/90-sma-config

The installation scripts check which variant and use a different set of packages. The build container or any container with SMA_HWACCEL set to true tries to install a broad set

That being said, I do not believe alpine has an equivalent of the non-free package

Are you using the build container with the HWACCEL collection of packages for radarr?

**Comment by mdhiggins** [comment]
Similarly, you shouldn't need to be manually installing that package for Sonarr docker container if properly set up since its included

**Comment by tjfriese** [comment]
Here is my .yml file for Sonarr:

services:
  Sonarr:
    image: mdhiggins/sonarr-sma:latest
    container_name: Sonarr
    environment:
      - PUID=1027
      - PGID=100
      - TZ=America/Winnipeg
      - SMA_HWACCEL=true
      - SMA_USE_REPO=true
    volumes:
      - /volume1/docker/Sonarr:/config
      - /volume1/Downloads/Media/TV:/tv
      - /volume1/Downloads/SMA/config:/usr/local/sma/config
      - /volume1/Downloads/Usenet:/downloads
    ports:
      - 8989:8989
    network_mode: synobridge
    restart: unless-stopped
    devices:
    - /dev/dri/:/dev/dri/
    
I did have to install the non-free driver to get the hardware acceleration to work, otherwise it would error.

Here is my Radarr .yml:

services:
  Radarr:
    image: mdhiggins/radarr-sma:latest
    container_name: Radarr
    environment:
      - PUID=1027
      - PGID=100
      - TZ=America/Winnipeg
      - SMA_HWACCEL=true
      - SMA_USE_REPO=true
    volumes:
      - /volume1/docker/Radarr:/config
      - /volume1/Downloads/Media/Movies:/movies
      - /volume1/Downloads/SMA/config:/usr/local/sma/config
      - /volume1/Downloads/Usenet:/downloads
    ports:
      - 7878:7878
    network_mode: synobridge
    restart: unless-stopped
    devices:
    - /dev/dri/:/dev/dri/

**Comment by mdhiggins** [comment]
What I'm saying is that for the Ubuntu based repositories (in this case Sonarr) if SMA_HWACCEL is true then the non free package should already be installed, so not sure why you would need to manually install it, I'd be curious if that actually did anything

https://github.com/mdhiggins/radarr-sma/blob/build/root/etc/cont-init.d/90-sma-config#L32

The other question is if the FFMPEG build from the repository (since you're using SMA_USE_REPO) is compiled to support VAAPI which varies and will differ across distros; if it does not support VAAPI you would probably be better served using the `build` tag and letting that handle your FFMPEG binary

But yeah to answer the actual initial question, Radarr is currently an alpine based image so it uses `apk` not `apt`
