### ISSUE TITLE
Add option for conversion timeout

### ISSUE THREAD

**Issue by joshdev8** [mdhiggins/radarr-sma#45]
I'm running into an issue with some files taking a very long time to process or just not converting at all. While this is happening my CPU is basically pegged at >90% until i restart the container or manually kill the process. Was wondering if you could add a timeout function to either cancel the conversion and just retain the original file or something like that.

**Comment by mdhiggins** [comment]
No plans for this. Need to address whatever is causing the underlying problem not just bandaid it with a timeout. It's most likely something that can be addressed by tweaking conversion parameters

Feel free to post some logs of a conversion that works versus one that's taking too long and I can tell you the difference. What kind of hardware you running

**Comment by joshdev8** [comment]
That's a good call. I've got a Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz 8 cores.

It looks like the conversion IS actually working, it just takes a really long time. But it did eventually complete.

Working conversion:
https://pastebin.com/gzMHSR1D

Long-running conversion:
https://pastebin.com/5XeTs1LL

**Comment by mdhiggins** [comment]
So your quick example is not doing any video encoding. It's just copying the stream directly which results in no CPU usage. The slow version looks like it's converting an HDR HEVC stream to H264 which is extremely CPU intensive especially on your relatively old CPU. 

You can add HEVC to your video codec list so it just copies it and then you'll be good or you can look into hardware encoding if you don't want HEVC though I think that series CPU/GPU quicksync probably won't handle HEVC but not 100% on that

Nothing actually wrong though, just two very different examples one the most efficient (remuxing) and one with probably the most demanding encoding scenarios you can create due to different source inputs

**Comment by joshdev8** [comment]
Ok great thank you for that info I will look into that. I may just get a new CPU I bought this one a while back. Do you have a particular CPU you'd recommend that would work well with a conversion like this as well as plex transcoding? I'll do some digging. Thanks for all your work on this it's a great tool!

**Comment by mdhiggins** [comment]
Tiger lake and onward supports most modern codecs and HDR profiles. Any Intel CPU with a built in GPU can handle this without breaking a sweat even a celeron or i3. I have an Intel NUC that has an N5105 that can do multiple 4K HDR transcodes in real time. Granted you'll need to read up on hardware acceleration but it's the way to go if you want to do any transcoding on 4K HDR material

**Comment by joshdev8** [comment]
Ok cool I will look into hardware acceleration but in the meantime have added hevc to my codec list and it resolved the CPU issue for now. I have a GTX 1660 super that I could probably use for HW acceleration I will look into that. If not I'll get a newer CPU. Thank you for your help!
