### ISSUE TITLE
FFMPEG in Radarr-sma cannot use INTEL QSV

### ISSUE THREAD

**Issue by lukasmd1989** [mdhiggins/radarr-sma#51]
I am running both radarr-sma and sonarr-sma in docker in the same machine, passing though my INTEL GPU. 

Hardware transcoding (h264_qsv and hevc_qsv) under sonarr-sma work flawlessly, but in radarr-sma it does not. After switching to another ffmpeg build I get at least the qsv encoder and decoder to showing up, but error while transcoding are persintent.

I noticed that a couple of weeks ago radarr-sma was reverted back from liunxserver/ffmpeg, while sonarr-sma is still using this build. Is there is chance to get radarr-sma back to linuxserver/ffmpeg?

log file: https://textbin.net/p7pqbsap6w

**Comment by mdhiggins** [comment]
Linuxservers FFMPEG container doesn't support alpine and their Radarr container is alpine based. The commit was reverted because it didn't work 

You should be able to use VAAPI without issue though which should be comparable performance wise to QSV (the repo included FFMPEG should support this, SMA_USE_REPO)

**Comment by lukasmd1989** [comment]
Thank you for you fast response. I wasn´t aware that linuxserver/radarr and linuxserver/sonarr are running in different systems. 

I will try VAAPI instead. Thank you.

**Comment by mdhiggins** [comment]
Most linuxserver containers are on alpine and it looks like the development branch of sonarr is on alpine as well so I imagine it will migrate over at some point (thought its been like that for over a year now)
